function InfoFruit() {
    let arr = [{"img":"ballpoint.jpeg","name":"ballpoint","status" : false,"price":30},
    {"img":"bookcase.jpeg","name":"bookcase","status" : false,"price":60},
    {"img":"brush.jpeg","name":"brush","status" : false,"price":48},
    {"img":"bulletin board.jpeg","name":"bulletin board","status" : false,"price":44},
    {"img":"calculator.jpeg","name":"calculator","status" : false,"price":40},
    {"img":"calendar.jpeg","name":"calendar","status" : false,"price":58},
    {"img":"chalk tray.jpeg","name":"chalk tray","status" : false,"price":56},
    {"img":"chalk.jpg","name":"chalk","status" : false,"price":57},
    {"img":"chalkboard.jpeg","name":"chalkboard","status" : false,"price":58},
    {"img":"cleaner.jpeg","name":"cleaner","status" : false,"price":50},
    {"img":"clock.jpeg","name":"clock","status" : false,"price":58},
    {"img":"computer.jpeg","name":"computer","status" : false,"price":60},
    {"img":"cubicle.jpeg","name":"cubicle","status" : false,"price":54},
    {"img":"desk.jpeg","name":"desk","status" : false,"price":57},
    {"img":"envelope.jpeg","name":"envelope","status" : false,"price":55},
    {"img":"eraser.jpg","name":"eraser","status" : false,"price":48},
    {"img":"file cabinet.jpeg","name":"file cabinet","status" : false,"price":54},
    {"img":"file clerk.jpeg","name":"file clerk","status" : false,"price":53},
    {"img":"file folder.jpeg","name":"file folder","status" : false,"price":58},
    {"img":"flag.jpeg","name":"flag","status" : false,"price":56},
    {"img":"glue.jpeg","name":"glue","status" : false,"price":47},
    {"img":"hall.jpeg","name":"hall","status" : false,"price":32},
    {"img":"headset.jpeg","name":"headset","status" : false,"price":58},
    {"img":"in-box.jpeg","name":"in-box","status" : false,"price":50},
    {"img":"legal pad.jpeg","name":"legal pad","status" : false,"price":33},
    {"img":"locker.jpeg","name":"locker","status" : false,"price":59},
    {"img":"loose-leaf paper.jpeg","name":"loose-leaf paper","status" : false,"price":57},
    {"img":"loudspeaker.jpeg","name":"loudspeaker","status" : false,"price":47},
    {"img":"manager.jpeg","name":"manager","status" : false,"price":47},
    {"img":"message pad.jpeg","name":"message pad","status" : false,"price":40},
    {"img":"overhead projector.jpeg","name":"overhead projector","status" : false,"price":50},
    {"img":"paper clips.jpeg","name":"paper clips","status" : false,"price":43},
    {"img":"pencil sharpener.jpeg","name":"pencil sharpener","status" : false,"price":57},
    {"img":"pencil.jpeg","name":"pencil","status" : false,"price":44},
    {"img":"photocopier.jpeg","name":"photocopier","status" : false,"price":60},
    {"img":"printer.jpeg","name":"printer","status" : false,"price":43},
    {"img":"printout.jpeg","name":"printout","status" : false,"price":58},
    {"img":"ring binder.jpeg","name":"ring binder","status" : false,"price":58},
    {"img":"rolodex.jpeg","name":"rolodex","status" : false,"price":56},
    {"img":"ruler.jpeg","name":"ruler","status" : false,"price":56},
    {"img":"secretary.jpeg","name":"secretary","status" : false,"price":53},
    {"img":"spiral-bound.jpeg","name":"spiral-bound","status" : false,"price":52},
    {"img":"staple remover.jpeg","name":"staple remover","status" : false,"price":30},
    {"img":"stapler.jpeg","name":"stapler","status" : false,"price":30},
    {"img":"switchboard operator.jpeg","name":"switchboard operator","status" : false,"price":46},
    {"img":"switchboard.jpeg","name":"switchboard","status" : false,"price":47},
    {"img":"telephone.jpeg","name":"telephone","status" : false,"price":56},
    {"img":"text book.jpeg","name":"text book","status" : false,"price":42},
    {"img":"thumbtack.jpeg","name":"thumbtack","status" : false,"price":47},
    {"img":"typewriter.jpeg","name":"typewriter","status" : false,"price":41},
    {"img":"typing chair.jpeg","name":"typing chair","status" : false,"price":53},
    {"img":"typist.jpeg","name":"typist","status" : false,"price":31},
    {"img":"word processor.jpeg","name":"word processor","status" : false,"price":51}]

    return arr
}

export default InfoFruit