function InfoFruit() {
    let arr = [{"img":"almond.jpeg","name":"almond","status": false,"price": 44 },
    {"img":"apple.jpeg","name":"apple","status": false,"price": 41 },
    {"img":"apricot.jpeg","name":"apricot","status": false,"price": 33 },
    {"img":"avocado.jpeg","name":"avocado","status": false,"price": 34 },
    {"img":"bananas.jpeg","name":"bananas","status": false,"price": 56 },
    {"img":"blackberries.jpeg","name":"blackberries","status": false,"price": 38 },
    {"img":"blueberries.jpeg","name":"blueberries","status": false,"price": 41 },
    {"img":"cantaloupe.jpeg","name":"cantaloupe","status": false,"price": 51 },
    {"img":"cashew.jpeg","name":"cashew","status": false,"price": 35 },
    {"img":"cherries.jpeg","name":"cherries","status": false,"price": 39 },
    {"img":"chestnut.jpeg","name":"chestnut","status": false,"price": 31 },
    {"img":"coconut.jpeg","name":"coconut","status": false,"price": 44 },
    {"img":"cranberries.jpeg","name":"cranberries","status": false,"price": 36 },
    {"img":"date.jpeg","name":"date","status": false,"price": 32 },
    {"img":"fig.jpeg","name":"fig","status": false,"price": 45 },
    {"img":"gooseberries.jpeg","name":"gooseberries","status": false,"price": 49 },
    {"img":"grapefruit.jpeg","name":"grapefruit","status": false,"price": 38 },
    {"img":"grapes.jpeg","name":"grapes","status": false,"price": 56 },
    {"img":"hazelnut.jpeg","name":"hazelnut","status": false,"price": 38 },
    {"img":"honeydew melon.jpeg","name":"honeydew melon","status": false,"price": 44 },
    {"img":"lemon.jpeg","name":"lemon","status": false,"price": 60 },
    {"img":"lime.jpeg","name":"lime","status": false,"price": 42 },
    {"img":"mango.jpeg","name":"mango","status": false,"price": 51 },
    {"img":"nectarine.jpeg","name":"nectarine","status": false,"price": 55 },
    {"img":"orange.jpeg","name":"orange","status": false,"price": 46 },
    {"img":"papaya.jpeg","name":"papaya","status": false,"price": 51 },
    {"img":"peach.jpeg","name":"peach","status": false,"price": 57 },
    {"img":"peanut.jpeg","name":"peanut","status": false,"price": 55 },
    {"img":"pear.jpeg","name":"pear","status": false,"price": 47 },
    {"img":"pineapple.jpeg","name":"pineapple","status": false,"price": 48 },
    {"img":"plum.jpeg","name":"plum","status": false,"price": 47 },
    {"img":"prune.jpeg","name":"prune","status": false,"price": 31 },
    {"img":"raisin.jpeg","name":"raisin","status": false,"price": 32 },
    {"img":"raspberries.jpeg","name":"raspberries","status": false,"price": 32 },
    {"img":"strawberry.jpeg","name":"strawberry","status": false,"price": 56 },
    {"img":"walnut.jpeg","name":"walnut","status": false,"price": 32 },
    {"img":"watermelon.jpeg","name":"watermelon","status": false,"price": 47 }]

    return arr
}

export default InfoFruit