function InfoFruit() {
    let arr = [{ "img": "electric drill.jpeg", "name": "electric drill", "status": false, "price": 44 },
    { "img": "electrical tape.jpeg", "name": "electrical tape", "status": false, "price": 49 },
    { "img": "extension lead.jpeg", "name": "extension lead", "status": false, "price": 30 },
    { "img": "glue.jpeg", "name": "glue", "status": false, "price": 43 },
    { "img": "grounding plug.jpeg", "name": "grounding plug", "status": false, "price": 37 },
    { "img": "hacksaw.jpeg", "name": "hacksaw", "status": false, "price": 58 },
    { "img": "hammer.jpeg", "name": "hammer", "status": false, "price": 43 },
    { "img": "hatchet.jpeg", "name": "hatchet", "status": false, "price": 32 },
    { "img": "hook.jpeg", "name": "hook", "status": false, "price": 36 },
    { "img": "jigsaw.jpeg", "name": "jigsaw", "status": false, "price": 58 },
    { "img": "mallet.jpeg", "name": "mallet", "status": false, "price": 36 },
    { "img": "monkey wrench.jpeg", "name": "monkey wrench", "status": false, "price": 53 },
    { "img": "nail.jpeg", "name": "nail", "status": false, "price": 47 },
    { "img": "nut.jpeg", "name": "nut", "status": false, "price": 45 },
    { "img": "outlet.jpeg", "name": "outlet", "status": false, "price": 47 },
    { "img": "paint.jpeg", "name": "paint", "status": false, "price": 53 },
    { "img": "paintbrush.jpeg", "name": "paintbrush", "status": false, "price": 49 },
    { "img": "pan.jpeg", "name": "pan", "status": false, "price": 36 },
    { "img": "pegboard.jpeg", "name": "pegboard", "status": false, "price": 32 },
    { "img": "Phillips screwdriver.jpeg", "name": "Phillips screwdriver", "status": false, "price": 38 },
    { "img": "pliers.jpeg", "name": "pliers", "status": false, "price": 34 },
    { "img": "power sander.jpeg", "name": "power sander", "status": false, "price": 42 },
    { "img": "roller.jpeg", "name": "roller", "status": false, "price": 39 },
    { "img": "router.jpeg", "name": "router", "status": false, "price": 55 },
    { "img": "sandpaper.jpeg", "name": "sandpaper", "status": false, "price": 33 },
    { "img": "saw.jpeg", "name": "saw", "status": false, "price": 35 },
    { "img": "scraper.jpeg", "name": "scraper", "status": false, "price": 32 },
    { "img": "screw.jpeg", "name": "screw", "status": false, "price": 50 },
    { "img": "screwdriver.jpeg", "name": "screwdriver", "status": false, "price": 52 },
    { "img": "tape measure.jpeg", "name": "tape measure", "status": false, "price": 31 },
    { "img": "toolbox.jpeg", "name": "toolbox", "status": false, "price": 49 },
    { "img": "vise.jpeg", "name": "vise", "status": false, "price": 37 },
    { "img": "washer.jpeg", "name": "washer", "status": false, "price": 31 },
    { "img": "wire.jpeg", "name": "wire", "status": false, "price": 49 },
    { "img": "wood plane.jpeg", "name": "wood plane", "status": false, "price": 31 },
    { "img": "wood.jpeg", "name": "wood", "status": false, "price": 53 },
    { "img": "workbench.jpeg", "name": "workbench", "status": false, "price": 43 },
    { "img": "wrench.jpeg", "name": "wrench", "status": false, "price": 35 },
    { "img": "bolt.jpeg", "name": "bolt", "status": false, "price": 33 },
    { "img": "brace.jpeg", "name": "brace", "status": false, "price": 34 },
    { "img": "carpenter's rule.jpeg", "name": "carpenter's rule", "status": false, "price": 41 },
    { "img": "C-clamp.jpeg", "name": "C-clamp", "status": false, "price": 49 },
    { "img": "circular saw.jpeg", "name": "circular saw", "status": false, "price": 38 }]
    return arr
}

export default InfoFruit