function InfoFruit() {
    let arr = [{ "img": "cone.jpeg", "name": "cone", "status": false, "price": 50 },
    { "img": "corn.jpeg", "name": "corn", "status": false, "price": 49 },
    { "img": "crocus.jpeg", "name": "crocus", "status": false, "price": 30 },
    { "img": "daffodil.jpeg", "name": "daffodil", "status": false, "price": 21 },
    { "img": "daisy.jpeg", "name": "daisy", "status": false, "price": 28 },
    { "img": "dogwood.jpeg", "name": "dogwood", "status": false, "price": 28 },
    { "img": "elm.jpeg", "name": "elm", "status": false, "price": 38 },
    { "img": "eucalyptus.jpeg", "name": "eucalyptus", "status": false, "price": 30 },
    { "img": "gardenia.jpeg", "name": "gardenia", "status": false, "price": 45 },
    { "img": "holly.jpeg", "name": "holly", "status": false, "price": 27 },
    { "img": "house plant.jpeg", "name": "house plant", "status": false, "price": 27 },
    { "img": "hyacinth.jpeg", "name": "hyacinth", "status": false, "price": 30 },
    { "img": "iris.jpeg", "name": "iris", "status": false, "price": 48 },
    { "img": "leaf.jpeg", "name": "leaf", "status": false, "price": 44 },
    { "img": "lily.jpeg", "name": "lily", "status": false, "price": 20 },
    { "img": "magnolia.jpeg", "name": "magnolia", "status": false, "price": 28 },
    { "img": "maple.jpeg", "name": "maple", "status": false, "price": 48 },
    { "img": "marigold.jpg", "name": "marigold", "status": false, "price": 44 },
    { "img": "needle.jpeg", "name": "needle", "status": false, "price": 37 },
    { "img": "oak.jpeg", "name": "oak", "status": false, "price": 40 },
    { "img": "oats.jpeg", "name": "oats", "status": false, "price": 28 },
    { "img": "orchid.jpeg", "name": "orchid", "status": false, "price": 20 },
    { "img": "palm.jpeg", "name": "palm", "status": false, "price": 37 },
    { "img": "pansy.jpeg", "name": "pansy", "status": false, "price": 48 },
    { "img": "petal.jpeg", "name": "petal", "status": false, "price": 26 },
    { "img": "petunia.jpeg", "name": "petunia", "status": false, "price": 35 },
    { "img": "pine.jpeg", "name": "pine", "status": false, "price": 26 },
    { "img": "poinsettia.jpeg", "name": "poinsettia", "status": false, "price": 50 },
    { "img": "poison ivy.jpeg", "name": "poison ivy", "status": false, "price": 31 },
    { "img": "poison oak.jpeg", "name": "poison oak", "status": false, "price": 41 },
    { "img": "poison sumac.jpeg", "name": "poison sumac", "status": false, "price": 33 },
    { "img": "poplar.jpeg", "name": "poplar", "status": false, "price": 50 },
    { "img": "redwood.jpeg", "name": "redwood", "status": false, "price": 37 },
    { "img": "rice.jpeg", "name": "rice", "status": false, "price": 48 },
    { "img": "root.jpeg", "name": "root", "status": false, "price": 49 },
    { "img": "rose.jpeg", "name": "rose", "status": false, "price": 44 },
    { "img": "sugar cane.jpeg", "name": "sugar cane", "status": false, "price": 23 },
    { "img": "sunflower.jpeg", "name": "sunflower", "status": false, "price": 37 },
    { "img": "thorn.jpeg", "name": "thorn", "status": false, "price": 45 },
    { "img": "tree.jpeg", "name": "tree", "status": false, "price": 48 },
    { "img": "trunk.jpeg", "name": "trunk", "status": false, "price": 25 },
    { "img": "tulip.jpeg", "name": "tulip", "status": false, "price": 26 },
    { "img": "twig.jpeg", "name": "twig", "status": false, "price": 49 },
    { "img": "vine.jpeg", "name": "vine", "status": false, "price": 43 },
    { "img": "violet.jpeg", "name": "violet", "status": false, "price": 21 },
    { "img": "wheat.jpeg", "name": "wheat", "status": false, "price": 28 },
    { "img": "willow.jpeg", "name": "willow", "status": false, "price": 20 },
    { "img": "zinnia.jpeg", "name": "zinnia", "status": false, "price": 39 },
    { "img": "acorn.jpeg", "name": "acorn", "status": false, "price": 35 },
    { "img": "bark.jpeg", "name": "bark", "status": false, "price": 44 },
    { "img": "birch.jpeg", "name": "birch", "status": false, "price": 37 },
    { "img": "branch.jpeg", "name": "branch", "status": false, "price": 43 },
    { "img": "bud.jpeg", "name": "bud", "status": false, "price": 36 },
    { "img": "bushes.jpeg", "name": "bushes", "status": false, "price": 29 },
    { "img": "buttercup.jpeg", "name": "buttercup", "status": false, "price": 44 },
    { "img": "cactus.jpeg", "name": "cactus", "status": false, "price": 36 }]


    return arr
}

export default InfoFruit